-
    name: "Source"
    href: "https://github.com/SpeciesFileGroup/taxonworks"
-
    name: "Docs"
    href: "https://docs.taxonworks.org"
-
    name: "Gitter"
    href: "https://gitter.im/SpeciesFileGroup/taxonworks"
-
    name: "Rubydoc"
    href: "https://rdoc.taxonworks.org"
-
    name: "API"
    href: "https://api.taxonworks.org"

