-
    name: "Source"
    href: "http://google.com"
-
    name: "Rubydoc"
    href: "http://google.com"
-
    name: "API"
    href: "http://google.com"
-
    name: "Gitter"
    href: "http://google.com"
-
    name: "Open Hub"
    href: "http://google.com"
