-
    name: "Source"
    href: "https://github.com/SpeciesFileGroup/taxonworksp"
-
    name: "Gitter"
    href: "https://gitter.im/SpeciesFileGroup/taxonworm"
-
    name: "Rubydoc"
    href: "http://google.com"
-
    name: "API"
    href: "http://google.com"
-
    name: "Open Hub"
    href: "http://google.com"
