-
    name: "Submit feedback"
    href: "https://github.com/SpeciesFileGroup/TaxonWorks/issues"
-
    name: "Start a project"
    href: "https://docs.taxonworks.org/guide/start-a-project.html"
-
    name: "Ask a question"
    href: "https://gitter.im/SpeciesFileGroup/taxonwork"
