-
    name: "Source"
    href: "https://github.com/SpeciesFileGroup/taxonworks"
-
    name: "Gitter"
    href: "https://gitter.im/SpeciesFileGroup/taxonworks"
-
    name: "Rubydoc"
    href: "http://www.rubydoc.info/github/SpeciesFileGroup/taxonworks"
-
    name: "API"
    href: "https://github.com/SpeciesFileGroup/taxonworks_api"
-
    name: "Open Hub"
    href: "https://www.openhub.net/p/taxonworks"
