-
    name: "Submit feedback"
    href: "https://github.com/SpeciesFileGroup/TaxonWorks/issues"
-
    name: "Request access"
    href: "https://github.com/SpeciesFileGroup/taxonworks_doc/blob/master/REGISTRY.md"
-
    name: "Ask a question"
    href: "https://gitter.im/SpeciesFileGroup/taxonworks"
