logo: logo.svg
title: TaxonWorks
titleLogo: images/taxonworks-white.svg
slogan: Describe Life.
introMarkdown: intro.md
benefitsTitle: A digital companion for discovering biodiversity
benefits1Markdown: benefits-1.md
benefits2Markdown: benefits-2.md
benefits3Markdown: benefits-3.md
benefits4Markdown: benefits-4.md
benefits5Markdown: benefits-5.md
scopeTitle: Like life, TaxonWorks is ever-evolving
scopeMarkdown: scope.md
scopeConfig: scope.yaml
gettingStartedTitle: Get started with TaxonWorks
gettingStarted1Markdown: gettingStarted-1.md
gettingStarted2Markdown: gettingStarted-2.md
footerLogo: images/inhs-footer-logo.png
navLogo: images/inhs-nav-logo.svg
navText: images/inhs-nav-text.svg
sponsor: Illinois Natural History Survey Prairie Research Institute
builtBy: Built by [Pixo](http://www.pixotech.com)
funding: TaxonWorks is funded in part by the [National Science Foundation](http://www.nsf.gov)
twitterUrl: https://twitter.com/TaxonWorks