logo: tree-logo-graphic.svg
logoMedium: tree-logo-graphic-medium.svg
logoSmall: tree-logo-graphic-small.svg
title: TaxonWorks
titleLogo: images/taxonworks-white.svg
slogan: Describe life.
introMarkdown: intro.md
benefitsTitle: A digital companion for discovering biodiversity
benefits1Markdown: benefits-1.md
benefits2Markdown: benefits-2.md
benefits3Markdown: benefits-3.md
benefits4Markdown: benefits-4.md
sponsorsConfig: sponsors.yaml
scopeTitle: Like life, TaxonWorks is ever-evolving
scopeMarkdown: scope.md
scopeConfig: scope.yaml
gettingStartedTitle: Get Started with
gettingStarted1Markdown: gettingStarted-1.md
gettingStarted2aMarkdown: gettingStarted-2a.md
gettingStarted2bMarkdown: gettingStarted-2b.md
gettingStartedLogo: images/taxonworks-black.svg
footerLogo: images/inhs-footer-logo.png
navLogo: images/inhs-nav-logo.svg
navText: images/inhs-nav-text.svg
sponsor: Illinois Natural History Survey Prairie Research Institute
builtBy: Built by [Pixo](http://www.pixotech.com)
funding: TaxonWorks is funded in part by the [National Science Foundation](http://www.nsf.gov)
twitterUrl: https://twitter.com/TaxonWorks
footerLinksCodeMarkdown: footerLinksCode.md
footerLinksContactMarkdown: footerLinksContact.md
footerLinksSocialMarkdown: footerLinksSocial.md