features:
    -
        name: Nomenclature
        status: upcoming
        description: Curate all levels of nomenclature with specific reference to the governing codes of nomenclature, plants and animals are covered. Rich and deep coverage of nomenclatural rules are included to ensure adequate metadata are provided. Produce highly annotated nomenclatural catalogs for print.
        whenComplete: this_year
        features:
            -
                name: Nomenclature Sub Feature
                status: upcoming
                description: Foo bar baz
                whenComplete: this_year
                features:
                    -
                        name: Nomenclature Sub Sub Feature
                        status: upcoming
                        description: This is a three deep feature
                        whenComplete: this_year
    -
        name: Taxon, specimen and anatomical descriptions
        status: upcoming
        description: Make descriptions and take notes using free-text, qualitative, quantitative (including measurements), or rich semantic data.
        whenComplete: three_year
    -
        name: 1995-1996 Chicago Bulls
        status: complete
        description: 72-10, Finished 1st in NBA Central Division
        whenComplete: now
        features:
            -
                name: Michael Jordan
                status: complete
                description: Michael Jeffrey Jordan (Mike, Air Jordan, M.J., His Airness, Money, Black Cat, G.O.A.T., Superman)
                whenComplete: now

            -
                name: Scottie Pippen
                status: complete
                description: Scottie Pippen (Pip, Scott, Batman, Robin)
                whenComplete: now
            -
                name: Dennis Rodman
                status: complete
                description: Dennis Rodman (The Worm, Dennis the Menace)
                whenComplete: now
            -
                name: Steve Kerr
                status: complete
                description: Stephen Douglas Kerr (Ice)
                whenComplete: now
            -
                name: Toni Kukoc
                status: complete
                description: Toni Kukoc (Croatian Sensation, The Waiter, Euro-Magic, The Pink Panther, Spider of Split, Kuki, Alien)
                whenComplete: now