features:
    -
        name: 1986 Boston Celtics
        status: in_progress
        description: 67-15, Finished 1st in NBA Atlantic Division
        whenComplete: this_year
        features:
            -
                name: Larry Bird
                status: upcoming
                description: Larry Legend, The Hick from French Lick, Kodak, The Great White Hope
                whenComplete: three_year
            -
                name: Kevin McHale
                status: upcoming
                description: Black Hole
                whenComplete: three_year
            -
                name: Dennis Johnson
                status: upcoming
                description: D.J., Airplane
                whenComplete: three_year
            -
                name: Robert Parish
                status: upcoming
                description: The Chief, Slim
                whenComplete: three_year
            -
                name: Danny Ainge
                status: upcoming
                description: Now the GM of the Celtics
                whenComplete: three_year
    -
        name: 1984-1985 Los Angeles Lakers
        status: upcoming
        description: 62-20, Finished 1st in NBA Pacific Division
        whenComplete: three_year
        features:
            -
                name: Magic Johnson
                status: upcoming
                description: Magic, Buck, E.J. the Deejay
                whenComplete: three_year
            -
                name: James Worthy
                status: upcoming
                description: Big Game James
                whenComplete: three_year
            -
                name: Kareem Abdul-Jabbar
                status: upcoming
                description: Lew, Cap, Murdock, Big Fella
                whenComplete: three_year
            -
                name: Byron Scott
                status: upcoming
                description: 6-3, 195lb (190cm, 88kg)
                whenComplete: three_year
            -
                name: Michael Cooper
                status: upcoming
                description: Coop, Mike
                whenComplete: three_year
    -
        name: 1995-1996 Chicago Bulls
        status: complete
        description: 72-10, Finished 1st in NBA Central Division
        whenComplete: now
        features:
            -
                name: Michael Jordan
                status: complete
                description: Michael Jeffrey Jordan (Mike, Air Jordan, M.J., His Airness, Money, Black Cat, G.O.A.T., Superman)
                whenComplete: now

            -
                name: Scottie Pippen
                status: complete
                description: Scottie Pippen (Pip, Scott, Batman, Robin)
                whenComplete: now
            -
                name: Dennis Rodman
                status: complete
                description: Dennis Rodman (The Worm, Dennis the Menace)
                whenComplete: now
            -
                name: Steve Kerr
                status: complete
                description: Stephen Douglas Kerr (Ice)
                whenComplete: now
            -
                name: Toni Kukoc
                status: complete
                description: Toni Kukoc (Croatian Sensation, The Waiter, Euro-Magic, The Pink Panther, Spider of Split, Kuki, Alien)
                whenComplete: now