-
    name: Sponsor 1
    src: "http://www.placebacon.net/400/300"
-
    name: Sponsor 2
    src: "http://www.placebacon.net/400/300"
-
    name: Sponsor 3
    src: "http://www.placebacon.net/400/300"
-
    name: Sponsor 4
    src: "http://www.placebacon.net/400/300"
-
    name: Sponsor 5
    src: "http://www.placebacon.net/400/300"
-
    name: Sponsor 6
    src: "http://www.placebacon.net/400/300"